### ISSUE TITLE
Бан на разные сроки

### ISSUE THREAD

**Issue by Miaka777** [Rabb1tof/WarnSystem#1]
Здравствуйте
Возможно реализовать бан на разные сроки в зависимости от того, за какие нарушения выдавались предупреждения?

**Comment by vadrozh** [comment]
Идея хорошая, пока не знаю как реализовать....

**Comment by CrazyHackGUT** [comment]
Вынеси в конфиг связанные с причинами команды, которые надо выполнить. Реализуй простейший токенайзер (чтобы **{USERID}** в команде из конфига превращался в реальный UserID наказанного игрока, и т.д.). И готово.

**Comment by WhyFaust** [comment]
Так же можно реализовать разные действия на разные причины
То есть причина есть плохой микрофон,и 3 предупреждения по этому пункту игроку дают мут,а не бан,как по стандарту.
Так же с другими

**Comment by WhyFaust** [comment]
Типо в конфиге вот так:
```
"1"
{
  "reason" "Плохой микрофон"  //Причина
  "type" "3"  //Действие 1-кик 2-бан 3-мут
  "time" "30"  //Время в минутах
  "flag" "b"  //Флаг админа для вывода причины
}
"2"
{
  "reason" "Нарушение правил"  //Причина
  "type" "2"  //Действие 1-кик 2-бан 3-мут
  "time" "10"  //Время в минутах
  "flag" "a"  //Флаг админа для вывода причины
}
```

**Comment by CrazJoker** [comment]
Иммунитет с админами учтён?:)да и по поводу сутра отличная идея + разное время для каждой причины.
И чтобы при получении нарушения, всчат игроку писало причину.
Сейчас пишет только стандарт " не нарушай правила....и тд"

**Comment by CrazJoker** [comment]
Кика*

**Comment by vadrozh** [comment]
@CrazJoker причины и прочее настраиваются в конфиге

**Comment by CrazJoker** [comment]
Я имел ввиду в меню чтобы можно выбрать причину и игроку ее и показывало. .потимпу вас забанили за аим или вх.
