### ISSUE TITLE
WS_Sourcebans plugin does not generate config

### ISSUE THREAD

**Issue by crashzk** [Rabb1tof/WarnSystem#13]
I activated the **WS_Sourcebans** plugin it is working fine, but it does not generate the config of it.

I tried to find in the folder that is configured in the script of the plugin:
``` 
AutoExecConfig(true, "sourcebans_support", "warnsystem");
```
But no files were generated, would that be correct?

How can I select which version of SourceBans to use in this case?

**Comment by Rabb1tof** [comment]
Hello!
Everything is much simpler, the code itself determines whether you use the SB(++)/MA or not. But it is better to recompile the code yourself, for example, if you don’t use the SB(++)/MA, then don’t throw in the libraries (.inc) and just compile.

This line: `AutoExecConfig(true, "sourcebans_support", "warnsystem");` is commented out now.

**Comment by crashzk** [comment]
I understand, thanks for the explanation.

Another question would be, in case it would not be better to generate the config again, so the user could choose the easiest version in case?

Or as you yourself said, since the plugin automatically detects which version you use is completely unnecessary?

**Comment by Rabb1tof** [comment]
You can make a version (or replace the current code) so that you can activate the necessary option by convar (SB, SB++ or MA).

**Comment by crashzk** [comment]
I see, thank you again.
