### ISSUE TITLE
Command WarnMenu

### ISSUE THREAD

**Issue by crashzk** [Rabb1tof/WarnSystem#14]
It would be possible to create the command `!warmenu` to open it right the WarnSystem Menu.

Currently I type it but nothing happens. 

This makes it easier to access the menu than just using the `!admin` command.

**Comment by Rabb1tof** [comment]
Hello, ok, i'll added.

**Comment by Rabb1tof** [comment]
@paulocrash, I'm added. Your task is to check.
Use `!warnmenu`.

**Comment by crashzk** [comment]
> @paulocrash, I'm added. Your task is to check.
> Use `!warnmenu`.

@Rabb1tof I tried to use it and unsuccessfully, I believe it is because it was not compiled with the latest version, would have to compile the plugin source file for it to work, right?

**Comment by Rabb1tof** [comment]
Yeah, I forgot to upload the file...

**Comment by Rabb1tof** [comment]
I close the issue. If that you can open it again.
