### ISSUE TITLE
Добавить новую функцию при максимальном количестве предупреждений.

### ISSUE THREAD

**Issue by xDavidos** [Rabb1tof/WarnSystem#16]
Добавь новую функцию, при максимальном количестве предупреждений, чтобы можно было выбрать ничего не делать, в sm_warns_maxpunishment.

**Comment by Rabb1tof** [comment]
Зачем? О_о

**Comment by xDavidos** [comment]
Просто я использую на свое сервере как одно предупреждения, а потом после повторного у же сам через меню Ma наказывать.

**Comment by Rabb1tof** [comment]
Имхо: можно просто повысить кол-во допустимых предупреждений и понизить время автоматического снятия варна.

**Comment by xDavidos** [comment]
Ну тогда, будет не понятно, было у человека предупреждения или нет если зайдет другой админ.

**Comment by Rabb1tof** [comment]
Нужно ли сбрасывать варны при этом?

**Comment by xDavidos** [comment]
Да

**Comment by xDavidos** [comment]
Спасибо

**Comment by Rabb1tof** [comment]
Залил, проверяй. Также проверь, пожалуйста, на чистой бд, если есть возможность, несколько серверов на одной бд.

**Comment by Davidos15** [comment]
Я сервер не перегружал, но карту менял, вот ошибка, базу удалял, когда выдаешь макс предов челе кикает, так же я удали старый кфг и в cfg не появилось четвертого пункта в плагин листе показывает версию 1.4.3.2
L 09/08/2019 - 21:19:12: [SM] Exception reported: Client index 4 is invalid (arg 4)
L 09/08/2019 - 21:19:12: [SM] Blaming: WarnSystem.smx
L 09/08/2019 - 21:19:12: [SM] Call stack trace:
L 09/08/2019 - 21:19:12: [SM]   [0] VFormat
L 09/08/2019 - 21:19:12: [SM]   [1] Line 174, .\WarnSystem.sp::PrintToAdmins
L 09/08/2019 - 21:19:12: [SM]   [2] Line 293, WarnSystem/database.sp::SQL_LoadPlayerData

**Comment by xDavidos** [comment]
Кароч тестил я его, всё работает, но иногда в консоль такие ошибки кидает, это версия 1.4.3.2
L 09/09/2019 - 21:17:13: [SM] Exception reported: Client index 29 is invalid (arg 4)
L 09/09/2019 - 21:17:13: [SM] Blaming: WarnSystem.smx
L 09/09/2019 - 21:17:13: [SM] Call stack trace:
L 09/09/2019 - 21:17:13: [SM]   [0] VFormat
L 09/09/2019 - 21:17:13: [SM]   [1] Line 174, .\WarnSystem.sp::PrintToAdmins
L 09/09/2019 - 21:17:13: [SM]   [2] Line 293, WarnSystem/database.sp::SQL_LoadPlayerData

**Comment by Rabb1tof** [comment]
Именно иногда? Не всегда?

**Comment by xDavidos** [comment]
Нет не всегда, ещё вот такое иногда пишет L 09/09/2019 - 21:23:55: [WarnSystem] SQL_CheckError: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UPDATE `ws_player` SET `warns` = '0' WHERE `account_id` = '297091623'' at line 1
