### ISSUE TITLE
Возможность мутов

### ISSUE THREAD

**Issue by schweppesss** [Rabb1tof/WarnSystem#19]
Будет ли в дальнейшем возможность мутов ? Просто за некоторые правила выдавать бан немного тупо. Типа сделать допустим максимум два предупреждения - первое предупреждение даёшь за правило за который даётся бан, а второе предупреждение за правило за которое даётся мут, и игрока мутит на время и за правило которое прописано в конфиге.

**Comment by Rabb1tof** [comment]
Для этого есть модуль `punish`.
