### ISSUE TITLE
Нельзя сбросить предупреждения командой

### ISSUE THREAD

**Issue by madwayz** [Rabb1tof/WarnSystem#4]
У меня флаг Z, в конфиге минимальный флаг стоит A, но на команду !resetwarn nick test сервер отвечает мне: "[WarnSystem] У вас нет доступа к этой команде". Через админку всё работает.

**Comment by vadrozh** [comment]
В версии 1.2 будет пофикшено.

**Comment by vadrozh** [comment]
Пофикшено в версии 1.2 ca8d162
