### ISSUE TITLE
Подрубить веб интерфейс

### ISSUE THREAD

**Issue by livindege** [Rabb1tof/WarnSystem#6]
А есть ли маза подрубить веб интерфейс и подрубить его к sourcbans к примеру хотя бы в деш на главный?
Выдал типу предупреждение, и на сайте отображается его ник, сколько был предупрежден, по причине, в какое время и кто выдал (админ).

По структуре:
Дата выдачи
Ник предупрежденного
Причина предупреждения
Сколько был раз предупрежден
Кто выдал предупреждение
На каком сервер было выдано предупреждение (как таково не все держат лишь один сервер)
(И если как токово подрубить стимайди и айпи адрес чтоб выден был, если возможно)

Чтоб не объяснять когда заходит на сервер тот же тип и такой спрашивает за что кикнул (не все же читают причину в табличке), а так получается хорошее доказательство и отличная замена простому кику)

**Comment by vadrozh** [comment]
найдите человека который сделает веб

**Comment by Rabb1tof** [comment]
Реализовано для приват-версии.
