### ISSUE TITLE
Плагин ещё поддерживается?

### ISSUE THREAD

**Issue by FelixKot** [Rabb1tof/WarnSystem#8]
Если плагин ещё не заброшен хотел сообщить о нескольких багах.
1. При слишком длинной причине или нике игрока его просто не заносит в базу (по крайней мере причины и ники короче некой длины заносятся, может ошибка и не в длине, я не имею понятия).
2. Если баг с пункта 1 в действии (из-за длинного ника в базе пустая строка), то при выходе игрока варн переходит тому, кто после него зашёл на сервер.
3. Неудобства из-за переноса строк в консоли при проверке варнов.

Предложения для мелких доработок:
1. Было бы неплохо сделать сообщения самому админу при sm_warns_printtochat "0". Чат пустой и не понятно сработал плагин или нет.
2. Можно добавить переменные {WARNS} - кол-во варнов игрока, {MAX_WARNS} - максимальное кол-во варнов до наказания, {ADMIN} - администратор, выдавший последний варн, {REASON} - причина последнего варна, для использования этих данных в WarnAgreement.cfg если кому-либо это нужно.

**Comment by FelixKot** [comment]
По поводу первого и второго бага, это из-за обновления в sm. Ф-ю sql_escapestring сломали.

**Comment by vadrozh** [comment]
@FelixKot плагин и так должен отправлять всем админам сообщение, в т.ч. тому кто дал варн

**Comment by Rabb1tof** [comment]
В новой версии будет поддержка в конфиге `{ADMIN} {REASON}` Остальное **возможно** будет позже.
